%YAML:1.2

#
x_bound_min: 0
x_bound_max: 800

y_bound_min: 0
y_bound_max: 800

# measurement noise standard deviation. Higher values result in smoother estimate
measStdDevX: 0.1
measStdDevY: 0.1

# process (state transition) noise standard deviation
processStdDevX: 0.01
processStdDevXdot: 0.01
processStdDevY: 0.01
processStdDevYdot: 0.01

